require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ApartmentSearchesController do

  # This should return the minimal set of attributes required to create a valid
  # ApartmentSearch. As you add validations to ApartmentSearch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ApartmentSearchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all apartment_searches as @apartment_searches" do
      apartment_search = ApartmentSearch.create! valid_attributes
      get :index, {}, valid_session
      assigns(:apartment_searches).should eq([apartment_search])
    end
  end

  describe "GET show" do
    it "assigns the requested apartment_search as @apartment_search" do
      apartment_search = ApartmentSearch.create! valid_attributes
      get :show, {:id => apartment_search.to_param}, valid_session
      assigns(:apartment_search).should eq(apartment_search)
    end
  end

  describe "GET new" do
    it "assigns a new apartment_search as @apartment_search" do
      get :new, {}, valid_session
      assigns(:apartment_search).should be_a_new(ApartmentSearch)
    end
  end

  describe "GET edit" do
    it "assigns the requested apartment_search as @apartment_search" do
      apartment_search = ApartmentSearch.create! valid_attributes
      get :edit, {:id => apartment_search.to_param}, valid_session
      assigns(:apartment_search).should eq(apartment_search)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ApartmentSearch" do
        expect {
          post :create, {:apartment_search => valid_attributes}, valid_session
        }.to change(ApartmentSearch, :count).by(1)
      end

      it "assigns a newly created apartment_search as @apartment_search" do
        post :create, {:apartment_search => valid_attributes}, valid_session
        assigns(:apartment_search).should be_a(ApartmentSearch)
        assigns(:apartment_search).should be_persisted
      end

      it "redirects to the created apartment_search" do
        post :create, {:apartment_search => valid_attributes}, valid_session
        response.should redirect_to(ApartmentSearch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved apartment_search as @apartment_search" do
        # Trigger the behavior that occurs when invalid params are submitted
        ApartmentSearch.any_instance.stub(:save).and_return(false)
        post :create, {:apartment_search => { "user_id" => "invalid value" }}, valid_session
        assigns(:apartment_search).should be_a_new(ApartmentSearch)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ApartmentSearch.any_instance.stub(:save).and_return(false)
        post :create, {:apartment_search => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested apartment_search" do
        apartment_search = ApartmentSearch.create! valid_attributes
        # Assuming there are no other apartment_searches in the database, this
        # specifies that the ApartmentSearch created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ApartmentSearch.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => apartment_search.to_param, :apartment_search => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested apartment_search as @apartment_search" do
        apartment_search = ApartmentSearch.create! valid_attributes
        put :update, {:id => apartment_search.to_param, :apartment_search => valid_attributes}, valid_session
        assigns(:apartment_search).should eq(apartment_search)
      end

      it "redirects to the apartment_search" do
        apartment_search = ApartmentSearch.create! valid_attributes
        put :update, {:id => apartment_search.to_param, :apartment_search => valid_attributes}, valid_session
        response.should redirect_to(apartment_search)
      end
    end

    describe "with invalid params" do
      it "assigns the apartment_search as @apartment_search" do
        apartment_search = ApartmentSearch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ApartmentSearch.any_instance.stub(:save).and_return(false)
        put :update, {:id => apartment_search.to_param, :apartment_search => { "user_id" => "invalid value" }}, valid_session
        assigns(:apartment_search).should eq(apartment_search)
      end

      it "re-renders the 'edit' template" do
        apartment_search = ApartmentSearch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ApartmentSearch.any_instance.stub(:save).and_return(false)
        put :update, {:id => apartment_search.to_param, :apartment_search => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested apartment_search" do
      apartment_search = ApartmentSearch.create! valid_attributes
      expect {
        delete :destroy, {:id => apartment_search.to_param}, valid_session
      }.to change(ApartmentSearch, :count).by(-1)
    end

    it "redirects to the apartment_searches list" do
      apartment_search = ApartmentSearch.create! valid_attributes
      delete :destroy, {:id => apartment_search.to_param}, valid_session
      response.should redirect_to(apartment_searches_url)
    end
  end

end
